package lab1.Absyn; // Java Package generated by the BNF Converter.

public class ADecl extends Arg {
  public final Type type_;
  public final ARest arest_;
  public ADecl(Type p1, ARest p2) { type_ = p1; arest_ = p2; }

  public <R,A> R accept(lab1.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.ADecl) {
      lab1.Absyn.ADecl x = (lab1.Absyn.ADecl)o;
      return this.type_.equals(x.type_) && this.arest_.equals(x.arest_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.arest_.hashCode();
  }


}
