package lab1.Absyn; // Java Package generated by the BNF Converter.

public class AId extends ARest {
  public final String id_;
  public final ARRest arrest_;
  public AId(String p1, ARRest p2) { id_ = p1; arrest_ = p2; }

  public <R,A> R accept(lab1.Absyn.ARest.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.AId) {
      lab1.Absyn.AId x = (lab1.Absyn.AId)o;
      return this.id_.equals(x.id_) && this.arrest_.equals(x.arrest_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.id_.hashCode())+this.arrest_.hashCode();
  }


}
