package lab1.Absyn; // Java Package generated by the BNF Converter.

public abstract class ARest implements java.io.Serializable {
  public abstract <R,A> R accept(ARest.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lab1.Absyn.AId p, A arg);
    public R visit(lab1.Absyn.AEmp p, A arg);

  }

}
