package lab1.Absyn; // Java Package generated by the BNF Converter.

public class ARInit extends ARRest {
  public final Exp exp_;
  public ARInit(Exp p1) { exp_ = p1; }

  public <R,A> R accept(lab1.Absyn.ARRest.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.ARInit) {
      lab1.Absyn.ARInit x = (lab1.Absyn.ARInit)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
