package lab1.Absyn; // Java Package generated by the BNF Converter.

public abstract class ARRest implements java.io.Serializable {
  public abstract <R,A> R accept(ARRest.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lab1.Absyn.ARInit p, A arg);
    public R visit(lab1.Absyn.AREmp p, A arg);

  }

}
