package lab1.Absyn; // Java Package generated by the BNF Converter.

public class DQua extends Def {
  public final ListId listid_;
  public DQua(ListId p1) { listid_ = p1; }

  public <R,A> R accept(lab1.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.DQua) {
      lab1.Absyn.DQua x = (lab1.Absyn.DQua)o;
      return this.listid_.equals(x.listid_);
    }
    return false;
  }

  public int hashCode() {
    return this.listid_.hashCode();
  }


}
