package lab1.Absyn; // Java Package generated by the BNF Converter.

public class DType extends Def {
  public final ListId listid_;
  public final String id_;
  public DType(ListId p1, String p2) { listid_ = p1; id_ = p2; }

  public <R,A> R accept(lab1.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.DType) {
      lab1.Absyn.DType x = (lab1.Absyn.DType)o;
      return this.listid_.equals(x.listid_) && this.id_.equals(x.id_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listid_.hashCode())+this.id_.hashCode();
  }


}
