package lab1.Absyn; // Java Package generated by the BNF Converter.

public class EChar extends Exp {
  public final Character char_;
  public EChar(Character p1) { char_ = p1; }

  public <R,A> R accept(lab1.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.EChar) {
      lab1.Absyn.EChar x = (lab1.Absyn.EChar)o;
      return this.char_.equals(x.char_);
    }
    return false;
  }

  public int hashCode() {
    return this.char_.hashCode();
  }


}
