package lab1.Absyn; // Java Package generated by the BNF Converter.

public class EMulStr extends Exp {
  public final ListString liststring_;
  public EMulStr(ListString p1) { liststring_ = p1; }

  public <R,A> R accept(lab1.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.EMulStr) {
      lab1.Absyn.EMulStr x = (lab1.Absyn.EMulStr)o;
      return this.liststring_.equals(x.liststring_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststring_.hashCode();
  }


}
