package lab1.Absyn; // Java Package generated by the BNF Converter.

public class EQua extends Exp {
  public final ListId listid_;
  public EQua(ListId p1) { listid_ = p1; }

  public <R,A> R accept(lab1.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.EQua) {
      lab1.Absyn.EQua x = (lab1.Absyn.EQua)o;
      return this.listid_.equals(x.listid_);
    }
    return false;
  }

  public int hashCode() {
    return this.listid_.hashCode();
  }


}
