package lab1.Absyn; // Java Package generated by the BNF Converter.

public abstract class Rest implements java.io.Serializable {
  public abstract <R,A> R accept(Rest.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lab1.Absyn.RStm p, A arg);
    public R visit(lab1.Absyn.REnd p, A arg);

  }

}
