package lab1.Absyn; // Java Package generated by the BNF Converter.

public class RStm extends Rest {
  public final ListStm liststm_;
  public RStm(ListStm p1) { liststm_ = p1; }

  public <R,A> R accept(lab1.Absyn.Rest.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.RStm) {
      lab1.Absyn.RStm x = (lab1.Absyn.RStm)o;
      return this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststm_.hashCode();
  }


}
