package lab1.Absyn; // Java Package generated by the BNF Converter.

public class SDecl extends Stm {
  public final Type type_;
  public final String id_;
  public SDecl(Type p1, String p2) { type_ = p1; id_ = p2; }

  public <R,A> R accept(lab1.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.SDecl) {
      lab1.Absyn.SDecl x = (lab1.Absyn.SDecl)o;
      return this.type_.equals(x.type_) && this.id_.equals(x.id_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.id_.hashCode();
  }


}
