package lab1.Absyn; // Java Package generated by the BNF Converter.

public class SDef extends Stm {
  public final Def def_;
  public SDef(Def p1) { def_ = p1; }

  public <R,A> R accept(lab1.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof lab1.Absyn.SDef) {
      lab1.Absyn.SDef x = (lab1.Absyn.SDef)o;
      return this.def_.equals(x.def_);
    }
    return false;
  }

  public int hashCode() {
    return this.def_.hashCode();
  }


}
