package lab1.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(lab1.Absyn.EInt p, A arg);
    public R visit(lab1.Absyn.EString p, A arg);
    public R visit(lab1.Absyn.EQua p, A arg);
    public R visit(lab1.Absyn.ELShift p, A arg);
    public R visit(lab1.Absyn.ERShift p, A arg);

  }

}
